"""ORM models for sub-proyek I.

All custom IDs use the ``{prefix}-{8hex}-{4hex}`` format generated by
:func:`src.db.ids.make_id`. The ORM doesn't auto-generate IDs — repositories
call ``make_id()`` and pass the value to the constructor.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from src.db.session import Base


class Country(Base):
    __tablename__ = "country"

    country_id: Mapped[str] = mapped_column(String(30), primary_key=True)
    country_name: Mapped[str] = mapped_column(String(60), unique=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class Company(Base):
    __tablename__ = "company"

    company_id: Mapped[str] = mapped_column(String(30), primary_key=True)
    company_name: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)
    company_country: Mapped[str] = mapped_column(String(60), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class Department(Base):
    __tablename__ = "department"

    department_id: Mapped[str] = mapped_column(String(30), primary_key=True)
    department_name: Mapped[str] = mapped_column(String(80), unique=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    positions: Mapped[list[Position]] = relationship(
        back_populates="department", cascade="all, delete-orphan"
    )


class Position(Base):
    __tablename__ = "position"
    __table_args__ = (
        UniqueConstraint("position_name", "department_id", name="uq_position_name_department"),
    )

    position_id: Mapped[str] = mapped_column(String(30), primary_key=True)
    position_name: Mapped[str] = mapped_column(String(120), nullable=False)
    department_id: Mapped[str] = mapped_column(
        String(30), ForeignKey("department.department_id", ondelete="CASCADE"), nullable=False
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    department: Mapped[Department] = relationship(back_populates="positions")


class Service(Base):
    __tablename__ = "service"

    service_id: Mapped[str] = mapped_column(String(30), primary_key=True)
    service_name: Mapped[str] = mapped_column(String(100), unique=True, nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    domain: Mapped[str | None] = mapped_column(String(100), nullable=True)
    tone: Mapped[str | None] = mapped_column(String(255), nullable=True)
    target_audience: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    glossary_terms: Mapped[list[GlossaryTerm]] = relationship(
        back_populates="service", cascade="all, delete-orphan"
    )
    style_examples: Mapped[list[StyleExample]] = relationship(
        back_populates="service", cascade="all, delete-orphan"
    )


class GlossaryTerm(Base):
    __tablename__ = "glossary_terms"
    __table_args__ = (
        Index("ix_glossary_terms_service_langs", "service_id", "source_lang", "target_lang"),
    )

    id: Mapped[Any] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    service_id: Mapped[str] = mapped_column(
        String(30), ForeignKey("service.service_id", ondelete="CASCADE"), nullable=False
    )
    source_term: Mapped[str] = mapped_column(String(255), nullable=False)
    source_lang: Mapped[str] = mapped_column(String(8), nullable=False)
    target_term: Mapped[str] = mapped_column(String(255), nullable=False)
    target_lang: Mapped[str] = mapped_column(String(8), nullable=False)
    context: Mapped[str | None] = mapped_column(Text, nullable=True)
    is_forbidden: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    priority: Mapped[int] = mapped_column(Integer, nullable=False, server_default="0")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    service: Mapped[Service] = relationship(back_populates="glossary_terms")


class StyleExample(Base):
    __tablename__ = "style_examples"
    __table_args__ = (
        Index("ix_style_examples_service_langs", "service_id", "source_lang", "target_lang"),
    )

    id: Mapped[Any] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    service_id: Mapped[str] = mapped_column(
        String(30), ForeignKey("service.service_id", ondelete="CASCADE"), nullable=False
    )
    source_text: Mapped[str] = mapped_column(Text, nullable=False)
    source_lang: Mapped[str] = mapped_column(String(8), nullable=False)
    target_text: Mapped[str] = mapped_column(Text, nullable=False)
    target_lang: Mapped[str] = mapped_column(String(8), nullable=False)
    tags: Mapped[list[str] | None] = mapped_column(ARRAY(String(255)), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    service: Mapped[Service] = relationship(back_populates="style_examples")


class Tenant(Base):
    __tablename__ = "tenant"
    # `uq_tenant_name` is declared at the table level (not via column-level
    # `unique=True`) so the constraint name matches migration 006 EXACTLY.
    # Column-level `unique=True` makes SQLAlchemy emit an unnamed constraint
    # that Postgres auto-names `tenant_tenant_name_key` — when the migration
    # explicitly names it `uq_tenant_name`, the test DB (built via
    # `Base.metadata.create_all`) and the real DB would end up with different
    # constraint names, which breaks any future `op.drop_constraint("uq_tenant_name", ...)`.
    __table_args__ = (
        UniqueConstraint("tenant_name", name="uq_tenant_name"),
        UniqueConstraint(
            "country_name",
            "company_name",
            "department_name",
            name="uq_tenant_ccd_names",
        ),
        Index("ix_tenant_api_key_hash", "api_key_hash"),
    )

    tenant_id: Mapped[str] = mapped_column(String(30), primary_key=True)
    tenant_name: Mapped[str] = mapped_column(String(150), nullable=False)
    country_name: Mapped[str] = mapped_column(String(60), nullable=False)
    company_name: Mapped[str] = mapped_column(String(100), nullable=False)
    department_name: Mapped[str] = mapped_column(String(80), nullable=False)
    # WHY no server_default: callers (seed scripts, admin endpoints) MUST stamp
    # this with the current Postgres `alembic_version.version_num` at insert
    # time. Audit field per ADR-054. NOT NULL ensures missing-stamp errors
    # fail loud at INSERT instead of silently writing NULL.
    alembic_version_at_create: Mapped[str] = mapped_column(String(60), nullable=False)
    api_key_hash: Mapped[str] = mapped_column(String(128), unique=True, nullable=False)
    jwt_active_token: Mapped[str | None] = mapped_column(Text, nullable=True)
    jwt_refreshed_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # No relationships — denormalized snapshots (sub-proyek K, ADR-053). FK
    # columns dropped in migration 006; lookups by name go through repositories.


class TenantProfile(Base):
    __tablename__ = "tenant_profile"
    __table_args__ = (
        UniqueConstraint(
            "tenant_name",
            "position_name",
            "service_name",
            name="uq_tenant_profile_tps_names",
        ),
        CheckConstraint("array_length(prompt_applied, 1) = 3", name="ck_prompt_applied_length"),
        Index("ix_tenant_profile_tenant_name", "tenant_name"),
    )

    profile_id: Mapped[str] = mapped_column(String(30), primary_key=True)
    tenant_name: Mapped[str] = mapped_column(String(150), nullable=False)
    service_name: Mapped[str] = mapped_column(String(100), nullable=False)
    position_name: Mapped[str] = mapped_column(String(120), nullable=False)
    allowed_language: Mapped[list[str] | None] = mapped_column(ARRAY(String(8)), nullable=True)
    prompt_applied: Mapped[list[str]] = mapped_column(ARRAY(String(30)), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # No relationships — denormalized snapshots (sub-proyek K, ADR-053).


class TenantPrompt(Base):
    __tablename__ = "tenant_prompts"
    __table_args__ = (
        CheckConstraint(
            "agent_type IN ('lang_detect_input','lang_detect_output','translate')",
            name="ck_tenant_prompts_agent_type",
        ),
    )

    prompt_id: Mapped[str] = mapped_column(String(30), primary_key=True)
    agent_type: Mapped[str] = mapped_column(String(40), unique=True, nullable=False)
    template: Mapped[str] = mapped_column(Text, nullable=False)
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_by: Mapped[str | None] = mapped_column(String(255), server_default="system")


class IsoLanguage(Base):
    __tablename__ = "iso_languages"

    code: Mapped[str] = mapped_column(String(8), primary_key=True)
    name: Mapped[str] = mapped_column(String(60), nullable=False)
    native_name: Mapped[str | None] = mapped_column(String(100), nullable=True)


class TranslationLog(Base):
    __tablename__ = "translation_logs"
    __table_args__ = (Index("ix_translation_logs_tenant_started", "tenant_id", "started_at"),)

    log_id: Mapped[Any] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    tenant_id: Mapped[str | None] = mapped_column(
        String(30), ForeignKey("tenant.tenant_id", ondelete="SET NULL"), nullable=True
    )
    profile_id: Mapped[str | None] = mapped_column(
        String(30), ForeignKey("tenant_profile.profile_id", ondelete="SET NULL"), nullable=True
    )
    source_text: Mapped[str] = mapped_column(Text, nullable=False)
    source_lang: Mapped[str | None] = mapped_column(String(8), nullable=True)
    target_lang: Mapped[str] = mapped_column(String(8), nullable=False)
    translated_text: Mapped[str | None] = mapped_column(Text, nullable=True)
    status: Mapped[str] = mapped_column(String(20), nullable=False)
    detected_source_lang: Mapped[str | None] = mapped_column(String(8), nullable=True)
    detected_output_lang: Mapped[str | None] = mapped_column(String(8), nullable=True)
    source_lang_mismatch: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    output_lang_mismatch: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    rendered_prompt: Mapped[str | None] = mapped_column(Text, nullable=True)
    agentic_activities: Mapped[list[dict[str, Any]] | None] = mapped_column(JSONB, nullable=True)
    model_id: Mapped[str | None] = mapped_column(String(100), nullable=True)
    input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    cost_usd: Mapped[Any | None] = mapped_column(Numeric(12, 6), nullable=True)
    cached: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    cache_key: Mapped[str | None] = mapped_column(String(64), nullable=True)
    latency_ms: Mapped[Any | None] = mapped_column(Numeric(10, 2), nullable=True)
    trace_id: Mapped[Any | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    batch_id: Mapped[Any | None] = mapped_column(UUID(as_uuid=True), nullable=True)
    batch_index: Mapped[int | None] = mapped_column(Integer, nullable=True)
    request_metadata: Mapped[dict[str, Any] | None] = mapped_column(JSONB, nullable=True)
    error_code: Mapped[str | None] = mapped_column(String(60), nullable=True)
    error_detail: Mapped[str | None] = mapped_column(Text, nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
