"""Alembic migration environment, async-aware.

This is the version generated by ``alembic init -t async`` and then trimmed to:
- read the DB URL from our Settings (single source of truth, not alembic.ini)
- point ``target_metadata`` at our SQLAlchemy ``Base`` so autogenerate sees models

Phase 1 has no models, so autogenerate will produce empty migrations until
Phase 3 introduces the Profile/Glossary tables. That's expected.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

from alembic import context
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from src.config.settings import get_settings

# Importing the models module is what registers them on ``Base.metadata`` —
# without it ``alembic revision --autogenerate`` would diff against an empty
# metadata and propose dropping every table. The ``noqa: F401`` tells ruff this
# import IS used (for the side effect, not the symbol).
from src.db import models  # noqa: F401
from src.db.session import Base

# Alembic Config object — gives access to values in alembic.ini.
config = context.config

# Inject the runtime DB URL so we don't commit it to alembic.ini.
config.set_main_option("sqlalchemy.url", get_settings().database_url)

# Standard Alembic logging setup.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Metadata target for autogenerate. Empty in Phase 1 (no models yet).
target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Generate SQL without connecting to a DB. Useful for CI dry-runs."""
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata)
    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    """Run migrations against an async engine.

    We have to bridge async <-> sync here because Alembic's migration runner is
    synchronous. ``run_sync`` blocks the event loop, but that's fine inside a
    migration: we're not serving traffic.
    """
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        future=True,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
